name = "api-master"
main = "index.js"
compatibility_date = "2024-03-26"
minify = true

[vars]
PROXY_LIST_URL = "https://raw.githubusercontent.com/FoolVPN-ID/Nautica/refs/heads/main/proxyList.txt"
SLAVE_ENDPOINTS = "https://api-support.kaiakun52.workers.dev/"
SLAVE_TOKEN = "slave"
MASTER_TOKEN = "master"
BATCH_SIZE = "23"
HEALTH_CHECK_TIMEOUT = "5000"
FORCE_TOKEN = "apii"

[[kv_namespaces]]
binding = "PROXY_CACHE"
id = "22b7a7552073455492f6177889d1c384"

[[kv_namespaces]]
binding = "GEO_CACHE"
id = "c53328d44e62488899debddf822e5a5c"
