# Common configuration for all environments
main = "index.js"
compatibility_date = "2024-03-26"
minify = true

# ==================================
#  Environment for MASTER Worker
# ==================================
[env.master]
name = "api-master"

[env.master.vars]
ROLE = "MASTER"
MASTER_ENDPOINT = "https://api-master.dongtelo75.workers.dev"
PROXY_LIST_URL = "https://raw.githubusercontent.com/FoolVPN-ID/Nautica/refs/heads/main/proxyList.txt"
SLAVE_ENDPOINTS = "https://api-support.kaiakun52.workers.dev/"
SLAVE_TOKEN = "slave"
MASTER_TOKEN = "master"
BATCH_SIZE = "23"
HEALTH_CHECK_TIMEOUT = "5000"
FORCE_TOKEN = "apii"
# A separate token for external support workers to report their stats via API
EXTERNAL_STATS_TOKEN = "external-support-secret"

[env.master.triggers]
crons = [
  "*/30 * * * *", # Run main health check every 30 minutes
  "*/15 * * * *"  # Run failover check every 15 minutes
]

[[env.master.kv_namespaces]]
binding = "PROXY_CACHE"
id = "22b7a7552073455492f6177889d1c384"

[[env.master.kv_namespaces]]
binding = "GEO_CACHE"
id = "c53328d44e62488899debddf822e5a5c"

# IMPORTANT: You must create this KV namespace first by running:
# `wrangler kv:namespace create SUPPORT_STATS`
# Then, copy the 'id' from the command's output into the 'id' field below.
[[env.master.kv_namespaces]]
binding = "SUPPORT_STATS"
id = "b08d2c10eb4c411595a71532565ea48c"

# This KV namespace is for tracking dispatched jobs for the failover mechanism.
[[env.master.kv_namespaces]]
binding = "DISPATCH_LOG"
id = "2ec1e090b53341c29a4ba3c1accb1fea"


# ===================================
#  Environment for SUPPORT Worker
# ===================================
[env.support]
name = "api-support"

[env.support.vars]
ROLE = "SUPPORT"
# The master's URL, so the support worker knows where to send results.
MASTER_ENDPOINT = "https://api-master.dongtelo75.workers.dev"
SLAVE_TOKEN = "slave" # To authenticate requests from the master (e.g., /check-batch, /lookup-geoip)
MASTER_TOKEN = "master" # To authenticate requests to the master (e.g., /submit-results)
HEALTH_CHECK_TIMEOUT = "5000"

# All support workers report their stats back to the master via this API endpoint.
STATS_REPORTING_ENDPOINT = "https://api-master.dongtelo75.workers.dev/report-stats"
# This token must match the EXTERNAL_STATS_TOKEN on the master worker.
EXTERNAL_STATS_TOKEN = "external-support-secret"

# An external support worker does not need any direct KV bindings.
# It communicates with the master exclusively through APIs for all stateful operations.
